#include "switch/types.h"
#include "switch/result.h"
#include "switch/gfx/gfx.h"
#include "switch/runtime/devices/console.h"
// #include "switch/arm/tls.h"
// #include "switch/kernel/svc.h"
// #include "switch/kernel/ipc.h"
#include "switch/services/applet.h"
// #include "switch/services/sm.h"
#include "switch/services/hid.h"
